#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rspec-support
Version  : 3.3.0
Release  : 7
URL      : https://rubygems.org/downloads/rspec-support-3.3.0.gem
Source0  : https://rubygems.org/downloads/rspec-support-3.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# RSpec::Support
`RSpec::Support` provides common functionality to `RSpec::Core`,
`RSpec::Expectations` and `RSpec::Mocks`. It is considered
suitable for internal use only at this time.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rspec-support-3.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-rspec-support.gemspec

%build
gem build rubygem-rspec-support.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rspec-support-3.3.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rspec-support-3.3.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/File/cdesc-File.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/Object/check_for_extra_spaces-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/Object/check_for_tab_characters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/Object/command_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/Object/expected_encoding%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/Object/have_successful_no_warnings_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/Object/load_all_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/CallerFilter/cdesc-CallerFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/CallerFilter/first_non_rspec_line-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/BlockSignature/cdesc-BlockSignature.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/BlockSignature/classify_parameters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/add_old_hunk_to_hunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/add_to_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/all_strings%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/any_multiline_strings%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/build_hunks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/cdesc-Differ.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/coerce_to_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/color%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/color_diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/diff_as_object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/diff_as_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/diffably_stringify-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/finalize_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/format_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/handle_encoding_errors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/hash_to_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/multiline%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/no_numbers%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/no_procs%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/normal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/object_to_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Differ/safely_flatten-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/DirectoryMaker/cdesc-DirectoryMaker.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/DirectoryMaker/directory_exists%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/DirectoryMaker/generate_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/DirectoryMaker/generate_stack-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/DirectoryMaker/mkdir_p-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/cdesc-EncodedString.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/detect_source_encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/matching_encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/pick_encoding-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/remove_invalid_bytes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/source_encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/split-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/EncodedString/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/FormattingSupport/cdesc-FormattingSupport.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/FormattingSupport/dedent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/FuzzyMatcher/arrays_match%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/FuzzyMatcher/cdesc-FuzzyMatcher.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/FuzzyMatcher/hashes_match%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/FuzzyMatcher/values_match%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/HunkGenerator/actual_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/HunkGenerator/build_hunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/HunkGenerator/cdesc-HunkGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/HunkGenerator/context_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/HunkGenerator/diffs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/HunkGenerator/expected_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/HunkGenerator/hunks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/HunkGenerator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/InSubProcess/cdesc-InSubProcess.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/InSubProcess/in_sub_process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/InSubProcess/in_sub_process_if_possible-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/LooseSignatureVerifier/SignatureWithKeywordArgumentsMatcher/cdesc-SignatureWithKeywordArgumentsMatcher.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/LooseSignatureVerifier/SignatureWithKeywordArgumentsMatcher/has_kw_args_in%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/LooseSignatureVerifier/SignatureWithKeywordArgumentsMatcher/invalid_kw_args_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/LooseSignatureVerifier/SignatureWithKeywordArgumentsMatcher/missing_kw_args_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/LooseSignatureVerifier/SignatureWithKeywordArgumentsMatcher/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/LooseSignatureVerifier/SignatureWithKeywordArgumentsMatcher/non_kw_args_arity_description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/LooseSignatureVerifier/SignatureWithKeywordArgumentsMatcher/valid_non_kw_args%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/LooseSignatureVerifier/cdesc-LooseSignatureVerifier.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/LooseSignatureVerifier/split_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/cdesc-MethodSignature.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/classify_parameters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/could_contain_kw_args%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/has_kw_args_in%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/invalid_kw_args_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/max_non_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/min_non_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/missing_kw_args_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/non_kw_args_arity_description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/optional_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/required_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignature/valid_non_kw_args%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/cdesc-MethodSignatureVerifier.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/error_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/invalid_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/missing_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/non_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/split_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/MethodSignatureVerifier/valid_non_kw_args%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/OS/cdesc-OS.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/OS/windows%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/OS/windows_file_path%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ObjectFormatter/cdesc-ObjectFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ObjectFormatter/format-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ObjectFormatter/format_date_time-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ObjectFormatter/format_time-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ObjectFormatter/prepare_for_inspection-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ObjectFormatter/prepare_hash-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RecursiveConstMethods/cdesc-RecursiveConstMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RecursiveConstMethods/const_defined_on%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RecursiveConstMethods/constants_defined_on-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RecursiveConstMethods/get_const_defined_on-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RecursiveConstMethods/normalize_const_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RecursiveConstMethods/recursive_const_defined%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RecursiveConstMethods/recursive_const_get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Ruby/cdesc-Ruby.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Ruby/jruby%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Ruby/mri%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Ruby/non_mri%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Ruby/rbx%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RubyFeatures/caller_locations_supported%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RubyFeatures/cdesc-RubyFeatures.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RubyFeatures/foo-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RubyFeatures/kw_args_supported%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RubyFeatures/module_prepends_supported%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RubyFeatures/optional_and_splat_args_supported%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RubyFeatures/required_kw_args_supported%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/RubyFeatures/supports_rebinding_module_methods%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ShellOut/cdesc-ShellOut.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ShellOut/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ShellOut/run_ruby_with_current_load_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ShellOut/shell_out-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/ShellOut/with_env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Spec/cdesc-Spec.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Spec/setup_simplecov-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Spec/start_simplecov-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/cdesc-StdErrSplitter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/has_output%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/reopen-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/reset%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/to_io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/verify_no_warnings%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StdErrSplitter/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/cdesc-StrictSignatureVerifier.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/error_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/invalid_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/missing_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/non_kw_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/split_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/StrictSignatureVerifier/valid_non_kw_args%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Version/cdesc-Version.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/VersionChecker/cdesc-VersionChecker.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/VersionChecker/check_version%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/VersionChecker/compare_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/VersionChecker/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/VersionChecker/parse_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/VersionChecker/raise_too_low_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/VersionChecker/too_low%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/VersionChecker/version_requirement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Warnings/cdesc-Warnings.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Warnings/deprecate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Warnings/warn_deprecation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Warnings/warn_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/Warnings/warning-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/WithIsolatedStdErr/cdesc-WithIsolatedStdErr.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/WithIsolatedStdErr/with_isolated_stderr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/cdesc-Support.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/define_optimized_require_for_rspec-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/deregister_matcher_definition-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/failure_notifier%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/failure_notifier-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/is_a_matcher%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/matcher_definitions-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/method_handle_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/notify_failure-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/register_matcher_definition-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/rspec_description_for_object-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/thread_local_data-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/Support/with_failure_notifier-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpec/cdesc-RSpec.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/allow_deprecation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/allow_warning-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/cdesc-RSpecHelpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/expect_deprecation_with_call_site-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/expect_deprecation_without_call_site-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/expect_no_deprecation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/expect_no_deprecations-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/expect_no_warnings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/expect_warn_deprecation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/expect_warn_deprecation_with_call_site-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/expect_warning_with_call_site-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/RSpecHelpers/expect_warning_without_call_site-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-support-3.3.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/Changelog.md
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/caller_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/differ.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/directory_maker.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/encoded_string.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/fuzzy_matcher.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/hunk_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/matcher_definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/method_signature_verifier.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/recursive_const_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/ruby_features.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec/deprecation_helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec/formatting_support.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec/in_sub_process.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec/library_wide_checks.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec/shell_out.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec/stderr_splitter.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec/string_matcher.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec/with_isolated_directory.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/spec/with_isolated_stderr.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/version_checker.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support/warnings.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rspec-support-3.3.0.gemspec
